// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createCookieStorage, shouldUseCookieStorage } from '@/lib/cookieStorage';

// Vite uses VITE_ prefix for environment variables exposed to client
// Support both VITE_ and NEXT_PUBLIC_ for backward compatibility
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || import.meta.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 
  import.meta.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY;

if (!SUPABASE_URL) {
  const error = new Error(
    'Missing Supabase URL. Please set VITE_SUPABASE_URL in your environment variables. ' +
    'If deploying to Vercel, add it in Project Settings > Environment Variables.'
  );
  console.error('❌ Configuration Error:', error.message);
  throw error;
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  const error = new Error(
    'Missing Supabase publishable key. Please set VITE_SUPABASE_PUBLISHABLE_KEY in your environment variables. ' +
    'If deploying to Vercel, add it in Project Settings > Environment Variables.'
  );
  console.error('❌ Configuration Error:', error.message);
  throw error;
}

// Use cookie storage for cross-subdomain auth when on production beyondrounds subdomains
const authStorage = shouldUseCookieStorage() ? createCookieStorage() : localStorage;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});